Jyu ga report
GSA/data.gov pull request #239
Opened 2017-09-21 16:25 UTC by John123Yu

2017-09-27 00:41 UTC, JJediny approved these changes
LGTM @FuhuXia @dano-reisys I'd merge but want to make sure there's no conflict with the encrypted vault with any other work. So on you all to merge

2017-10-02 18:15 UTC, FuhuXia requested changes
Questionable change on ansible/roles/software/catalog/ckan-db-init/tasks/main.yml. Please verify the command works.

2017-10-02 18:42 UTC, FuhuXia approved these changes

2017-10-09 01:42 UTC, merged

2017-10-11 19:24 UTC, alex-perfilov-reisys commented
WP build is broken on bsp. Why is Wordpress involved here ?